make it to bandit

diff --git a/.github/workflows/security.yaml b/.github/workflows/security.yaml
--- a/.github/workflows/security.yaml
+++ b/.github/workflows/security.yaml
@@ -33,11 +33,21 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
-      - name: Deploy Flask App
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install dependencies
         run: |
           pip install --upgrade pip && pip install -r requirements.txt
-          python app.py &
-          sleep 5
+      - name: Start Flask App
+        run: |
+          nohup python app.py > app.log 2>&1 &
+          sleep 10
+          curl --retry 5 --retry-connrefused --silent --fail http://localhost:8000 || (echo "Flask app failed to start" && exit 1)
+      - name: Pull ZAP Docker Image (Fixes Permission Issues)
+        run: |
+          docker pull ghcr.io/zaproxy/zaproxy:stable
       - name: OWASP ZAP Scan
         uses: zaproxy/action-full-scan@v0.12.0
         with:
